include: package:lint/analysis_options.yaml

linter:
  rules:
    - sort_constructors_first

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    sort_constructors_first: error
